spring:
  application:
    name: ReimbursementAPI
  datasource:
    username: postgres
    password: 78411487
    url: jdbc:postgresql://34.66.198.242:5432/postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 3000
  servlet:
    context-path: /api-one