spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: metrics, prometheus
