spring:
  application:
    name: MyMediaAPI
  datasource:
    username: postgres
    password: p@$$w0rd123
    url: jdbc:postgresql://35.226.133.168:5432/my_media
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect




services:
  message-service:
    message: 'Hello, World!!!'
server:
  port: 3000
  servlet:
    context-path: /api